### ISSUE TITLE
Client and server 

### ISSUE THREAD

**Issue by ap9389552** [lukedukeus/esp32-bacnet-master-v5.01#3]
I'm using two same esp32 , and i uploaded the same code but it saying ADPU Timeout! . How to make one esp32 client and another server ?

**Comment by lukedukeus** [comment]
Take a look at the Kconfig.projbuild, or run `idf.py menuconfig`. Then you can change the `SERVER_DEVICE_ID` and `CLIENT_DEVICE_ID` on the esp32s. See: https://github.com/lukedukeus/esp32-bacnet-master-v5.01/blob/main/main/Kconfig.projbuild#L43. The idea is that one esp32 will have a server id of 200003 and client id of 200004, and the other esp32 will have server id of 200004 and client id of 200003.

**Comment by ap9389552** [comment]
![Screenshot (5)](https://github.com/lukedukeus/esp32-bacnet-master-v5.01/assets/85502292/bb28595b-aa66-4657-a8e4-209e16f3a53d)
I change the server as well as client id but still i'm getting the error APDU Timeout!

**Comment by lukedukeus** [comment]
This demo is hardcoded to work with the 192.16.1.X range, but I see that your esp32 is getting an IP of 192.168.188.148, which means the broadcast address of 192.168.1.255 is wrong. 

I've updated the code so that it should automatically grab the correct range when the `bip_set_interface` method is called, however, if you connect to wifi later, or it still gets the wrong address, you can hardecode that info in the `bip-init.c` file

**Comment by ap9389552** [comment]
Thanks for your response . Actually I'm creating a node there user only have to config to get the output .And they can use all the properties of bacnet , any suggestion ??

**Comment by lukedukeus** [comment]
I'm not sure what you mean, can you elaborate more?

**Comment by ap9389552** [comment]
Suppose I have a bacnet block for esp32 that can read and write . I dont understand what things require to make it possible . I want understand what data ,command etc requires from code to make it possible

**Comment by lukedukeus** [comment]
That will depend on what action you are trying to do. If you want to read a property, you will need a device id, object type, object instance, property identifier, and array index. To write, you will need all that, as well as tha value you want to write. Also, before reading or writing, you will need to do a one time initialization to setup the bacnet-stack and event handlers, or you could modify the code, so that it does setup when you call your read / write function.

**Comment by ap9389552** [comment]
Right now the code is for only read and write analog value . If i want to more bacnet object then what I need to change? And how i check from Yabe that what devices are on my network?

**Comment by lukedukeus** [comment]
Using Yabe, click on the plus in the top left corner, then click start next to your ip, and it will show all bacnet devices on the network:
![image](https://github.com/lukedukeus/esp32-bacnet-master-v5.01/assets/23089287/81638007-8324-4490-80c7-d2ba9eed6c02)


For changing what properties exist on the device, you have to change the `Object_Table` in main.c. For changing what value you are reading, you will have to change the `Send_Write_Property_Request` call in client_task.c
